### ISSUE TITLE
Compatible with 8.2.2?

### ISSUE THREAD

**Issue by keithslater** [getsentry/sentry-jira#104]
Does this work with sentry 8.2.2? I installed it but it doesn't show up in sentry under Issue Tracking or Manage Integrations.

However when I run sentry plugins list, it does show - 

sentry-hipchat 0.6.0
sentry-jira 0.12.0.dev0

**Comment by dcramer** [comment]
If it's not showing up it's likely because you didn't restart the processes

**Comment by keithslater** [comment]
I've actually restarted the server completely several times thinking that could be the problem.

**Comment by dcramer** [comment]
Does it show under the manage integrations tab? It's either not being picked up by the process or the version installed is erroring out on startup.

**Comment by keithslater** [comment]
It doesn't. Is there a log or something to see if it is erroring out?

**Comment by dcramer** [comment]
@keithslater there is stdout/stderr

**Comment by dcramer** [comment]
Though actually i think if 'sentry plugins list' works then it wouldn't be erroring out.

I can't tell you why it would be listed in plugins but not in the UI unless its not installed in the same environment that the web processes are running in.

**Comment by keithslater** [comment]
So I wanted to make sure that there wasn't two different environments. I checked inside of the Sentry environment web interface to see what the config file was then I ran 

sentry --config ~/.sentry/sentry.conf.py plugins list

Which matches the web interface config file and it is returning the same thing

sentry-hipchat 0.6.0
sentry-jira 0.12.0.dev0

Then I ran locate on a couple things -

> locate jira
> /usr/lib/python2.7/site-packages/sentry_jira
> /usr/lib/python2.7/site-packages/sentry_jira-0.12.0.dev0-py2.7.egg-info
> /usr/lib/python2.7/site-packages/sentry_jira/**init**.py
> /usr/lib/python2.7/site-packages/sentry_jira/**init**.pyc
> /usr/lib/python2.7/site-packages/sentry_jira/forms.py
> /usr/lib/python2.7/site-packages/sentry_jira/forms.pyc
> /usr/lib/python2.7/site-packages/sentry_jira/jira.py
> /usr/lib/python2.7/site-packages/sentry_jira/jira.pyc
> /usr/lib/python2.7/site-packages/sentry_jira/models.py
> /usr/lib/python2.7/site-packages/sentry_jira/models.pyc
> /usr/lib/python2.7/site-packages/sentry_jira/plugin.py
> /usr/lib/python2.7/site-packages/sentry_jira/plugin.pyc
> /usr/lib/python2.7/site-packages/sentry_jira/templates
> /usr/lib/python2.7/site-packages/sentry_jira/templates/sentry_jira
> /usr/lib/python2.7/site-packages/sentry_jira/templates/sentry_jira/create_jira_issue.html
> /usr/lib/python2.7/site-packages/sentry_jira/templates/sentry_jira/plugin_misconfigured.html
> /usr/lib/python2.7/site-packages/sentry_jira/templates/sentry_jira/project_conf_form.html
> /usr/lib/python2.7/site-packages/sentry_jira-0.12.0.dev0-py2.7.egg-info/PKG-INFO
> /usr/lib/python2.7/site-packages/sentry_jira-0.12.0.dev0-py2.7.egg-info/SOURCES.txt
> /usr/lib/python2.7/site-packages/sentry_jira-0.12.0.dev0-py2.7.egg-info/dependency_links.txt
> /usr/lib/python2.7/site-packages/sentry_jira-0.12.0.dev0-py2.7.egg-info/entry_points.txt
> /usr/lib/python2.7/site-packages/sentry_jira-0.12.0.dev0-py2.7.egg-info/installed-files.txt
> /usr/lib/python2.7/site-packages/sentry_jira-0.12.0.dev0-py2.7.egg-info/not-zip-safe
> /usr/lib/python2.7/site-packages/sentry_jira-0.12.0.dev0-py2.7.egg-info/requires.txt
> /usr/lib/python2.7/site-packages/sentry_jira-0.12.0.dev0-py2.7.egg-info/top_level.txt
> 
> locate hipchat
> /usr/lib/python2.7/site-packages/sentry_hipchat
> /usr/lib/python2.7/site-packages/sentry_hipchat-0.6.0-py2.7.egg-info
> /usr/lib/python2.7/site-packages/sentry_hipchat/**init**.py
> /usr/lib/python2.7/site-packages/sentry_hipchat/**init**.pyc
> /usr/lib/python2.7/site-packages/sentry_hipchat/models.py
> /usr/lib/python2.7/site-packages/sentry_hipchat/models.pyc
> /usr/lib/python2.7/site-packages/sentry_hipchat-0.6.0-py2.7.egg-info/PKG-INFO
> /usr/lib/python2.7/site-packages/sentry_hipchat-0.6.0-py2.7.egg-info/SOURCES.txt
> /usr/lib/python2.7/site-packages/sentry_hipchat-0.6.0-py2.7.egg-info/dependency_links.txt
> /usr/lib/python2.7/site-packages/sentry_hipchat-0.6.0-py2.7.egg-info/entry_points.txt
> /usr/lib/python2.7/site-packages/sentry_hipchat-0.6.0-py2.7.egg-info/installed-files.txt
> /usr/lib/python2.7/site-packages/sentry_hipchat-0.6.0-py2.7.egg-info/not-zip-safe
> /usr/lib/python2.7/site-packages/sentry_hipchat-0.6.0-py2.7.egg-info/pbr.json
> /usr/lib/python2.7/site-packages/sentry_hipchat-0.6.0-py2.7.egg-info/requires.txt
> /usr/lib/python2.7/site-packages/sentry_hipchat-0.6.0-py2.7.egg-info/top_level.txt
> /var/www/sentry/lib/python2.7/site-packages/sentry_hipchat
> /var/www/sentry/lib/python2.7/site-packages/sentry_hipchat-0.6.0-py2.7.egg-info
> /var/www/sentry/lib/python2.7/site-packages/sentry_hipchat/**init**.py
> /var/www/sentry/lib/python2.7/site-packages/sentry_hipchat/**init**.pyc
> /var/www/sentry/lib/python2.7/site-packages/sentry_hipchat/models.py
> /var/www/sentry/lib/python2.7/site-packages/sentry_hipchat/models.pyc
> /var/www/sentry/lib/python2.7/site-packages/sentry_hipchat-0.6.0-py2.7.egg-info/PKG-INFO
> /var/www/sentry/lib/python2.7/site-packages/sentry_hipchat-0.6.0-py2.7.egg-info/SOURCES.txt
> /var/www/sentry/lib/python2.7/site-packages/sentry_hipchat-0.6.0-py2.7.egg-info/dependency_links.txt
> /var/www/sentry/lib/python2.7/site-packages/sentry_hipchat-0.6.0-py2.7.egg-info/entry_points.txt
> /var/www/sentry/lib/python2.7/site-packages/sentry_hipchat-0.6.0-py2.7.egg-info/installed-files.txt
> /var/www/sentry/lib/python2.7/site-packages/sentry_hipchat-0.6.0-py2.7.egg-info/not-zip-safe
> /var/www/sentry/lib/python2.7/site-packages/sentry_hipchat-0.6.0-py2.7.egg-info/pbr.json
> /var/www/sentry/lib/python2.7/site-packages/sentry_hipchat-0.6.0-py2.7.egg-info/requires.txt
> /var/www/sentry/lib/python2.7/site-packages/sentry_hipchat-0.6.0-py2.7.egg-info/top_level.txt

So it does look like there are two environments. I'm not really sure how to correct the issue. Project root according to the web interface is '/var/www/sentry/lib/python2.7/site-packages/sentry-8.2.2-py2.7.egg/sentry'

**Comment by dcramer** [comment]
The /usr/lib env is what happens if you install a dependency without activating the virtualenv first. `source /var/www/sentry/bin/activate` before installing sentry-jira

**Comment by keithslater** [comment]
That fixed it. Thanks
