### ISSUE TITLE
future  one  configuration  for  all  projects

### ISSUE THREAD

**Issue by saytik** [getsentry/sentry-jira#118]
I have   installed  plugin,  but  it  is  many  clicks   to  configure  JIRA  for  every  project  in  sentry. 
It  would  be  good to  configure one  time   plugin  and  then enable integration  for  every  project    via checkbox  ...

**Comment by dcramer** [comment]
I agree, but it's a fairly complex scenario right now to support that kind of behavior.

I'm closing this out as we don't use the issue tracker for feature requests, but this is always on our radar and when we come up with a solution that doesn't cause problems with larger teams we're definitely going to solve it.
