### ISSUE TITLE
Can't configure sentry-jira

### ISSUE THREAD

**Issue by nihn** [getsentry/sentry-jira#68]
Hi,

when i'm trying to configure sentry-jira by filling JIRA Instance URL, username and password and then clicking 'Save changes' nothing happens. Server response is 200 OK. Im using new Sentry 7.5.0.

**Comment by dcramer** [comment]
Which version of Sentry?

**Comment by dcramer** [comment]
Also likely because we need to pull this upstream https://github.com/getsentry/sentry-jira/commit/5d94f469545f39e8835a25b90c8e2b2aa5ed1790

**Comment by nihn** [comment]
7.5.0

**Comment by vbjordan** [comment]
Also having this issue, plugin seems to be broken in 7.5...

**Comment by dcramer** [comment]
The released version is broken in 7.5, yes. @thurloat if you want to give me commit and pypi access (assuming I dont have it) I'll push out the updated version.

We couldn't easily make this backwards compat w/ the new dedicated settings pages.

**Comment by thurloat** [comment]
You have access to pypi now @dcramer, you already had commit access.

**Comment by dcramer** [comment]
I pushed out 0.9.0
