### ISSUE TITLE
Sentry v7.6.2  FORM POST issues

### ISSUE THREAD

**Issue by rogerhu** [getsentry/sentry-jira#70]
The Sentry plugin is currently broken on newer versions because an additional plugin form input needs to be passed along... see hearsaycorp/sentry-jira@c91b5fd (and the commit that broke stuff getsentry/sentry@68a30d9)

**Comment by rocktavious** [comment]
I finding this same issue with latest sentry.  I'll try the recommended fix and report back

**Comment by rocktavious** [comment]
It looks like this was implemented in the master branch, i'm going to test with that.  Would be nice to create a release of the master branch.

**Comment by dcramer** [comment]
This was resolved
