### ISSUE TITLE
Doesn't work with Sentry 7.7.1

### ISSUE THREAD

**Issue by Rambomst** [getsentry/sentry-jira#73]
As the title says, it appears this plugin doesn't work with the latest version on Sentry. I have installed it but have no JIRA menu item in the projects settings area.

**Comment by ssro** [comment]
Facing the same issue

**Comment by stayallive** [comment]
Here too :( I do have a JIRA menu but it doesn't save my credentials or gives any error/notice.

**Comment by dcramer** [comment]
Closing this out as Sentry 7.x is no longer supported
