### ISSUE TITLE
Doesn't work with Sentry Sentry 8.0.0rc1

### ISSUE THREAD

**Issue by mlavkin** [getsentry/sentry-jira#77]
Url like this /sentry/serviceportal/issues/7/actions/jira/ - only empty sentry template displayed.
In Jira log i found requests 
GET /rest/api/2/priority
GET /rest/api/2/project/TLS/versions
GET /rest/api/2/issue/createmeta?projectKeys=TLS&expand=projects.issuetypes.fields

**Comment by thebogusman** [comment]
+1

**Comment by nihn** [comment]
+1 (Sentry v.8.0.1)

**Comment by jacoor** [comment]
+1.

**Comment by jacoor** [comment]
I confirm it works when you use @hfietz pull request. Actually I used  hfietz/sentry-jira master branch.
Thank you @hfietz!

**Comment by nihn** [comment]
@dcramer will you release @hfietz fix?

**Comment by dcramer** [comment]
master works with 8 -- will get a release out once we fully QA current build

**Comment by jacoor** [comment]
thanks for the  update!

2016-02-08 21:05 GMT+01:00 David Cramer notifications@github.com:

> master works with 8 -- will get a release out once we fully QA current
> build
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/getsentry/sentry-jira/issues/77#issuecomment-181507207
> .

## 

Jacek Ostański
Internet Evolution - Strony i serwisy Internetowe
608-230-735
