### ISSUE TITLE
https://JIRA_URL/rest/api/2/priority matches the URL blacklist

### ISSUE THREAD

**Issue by Grovespaz** [getsentry/sentry-jira#79]
When setting up a project on the latest version of Sentry (8.0.1) it fails with the following exception:
Error in request to https://JIRA_URL/rest/api/2/priority: https://JIRA_URL/rest/api/2/priority matches the URL blacklist

(where JIRA_URL is our Jira URL)

**Comment by dcramer** [comment]
This is likely going to be a common story for on-premise.

You need to change `SENTRY_DISALLOWED_IPS`. If your install is closed to the public, just set it to `SENTRY_DISALLOWED_IPS = ()`.

**Comment by Grovespaz** [comment]
Thanks, modifying our SENTRY_DISALLOWED_IPS fixed it.
