### ISSUE TITLE
Blank screen when clicking Create issue in Jira

### ISSUE THREAD

**Issue by Grovespaz** [getsentry/sentry-jira#82]
When attempting to create a new Jira issue from a Sentry issue, Sentry responds with a near-blank page:
![image](https://cloud.githubusercontent.com/assets/2829264/12921432/98d91b14-cf4d-11e5-9ff7-b779572618b9.png)

Developer-tools shows only the following:
![image](https://cloud.githubusercontent.com/assets/2829264/12921466/bc8e20fe-cf4d-11e5-8c41-e2e75b49b511.png)

**Comment by dcramer** [comment]
@Grovespaz Are you on Sentry 8? You may need to install sentry-jira from GitHub until we release a new tag:

pip install https://github.com/getsentry/sentry-jira/archive/master.zip

**Comment by ghost** [comment]
Hi all! 
Got same issue, Sentry 8.1.2, jira-sentry 0.11.0.dev0

**Comment by dcramer** [comment]
I'm unable to reproduce this on Sentry 8.  This is on the "create issue" link from issue details?

**Comment by ghost** [comment]
Yep. 
I'm new Sentry user, installed latest version 2 days ago.
My Jira version is 6.4.11
I see only 3 queries to Jira from Sentry:

```
x.x.x.x 1133x130257x1 user [17/Feb/2016:18:53:49 +0300] "GET /rest/api/2/priority HTTP/1.1" 200 1248 449 "-" "sentry/8.1.2 (https://getsentry.com)" "1392x0x"
x.x.x.x 1133x130258x1 user [17/Feb/2016:18:53:50 +0300] "GET /rest/api/2/project/GN/versions HTTP/1.1" 200 16912 531 "-" "sentry/8.1.2 (https://getsentry.com)" "16r6vvt"
x.x.x.x 1133x130259x1 user [17/Feb/2016:18:53:51 +0300] "GET /rest/api/2/issue/createmeta?projectKeys=GN&expand=projects.issuetypes.fields HTTP/1.1" 200 664269 1270 "-" "sentry/8.1.2 (https://getsentry.com)" "1eygomi"
```

**Comment by dcramer** [comment]
Are you 100% certain the footer of the site says Sentry 8+? If so, can you try:

```
# run this until it says its not installed anymore
pip uninstall sentry-jira

# reinstall the latest git release
pip install https://github.com/getsentry/sentry-jira/archive/master.zip
```

I cant come up with any sane way that the code thats on GitHub could possibly be breaking at this point, since Sentry 8 is what we run in prod, and we are running latest sentry-jira as well.

**Comment by ghost** [comment]
After unistall / install plugin everything works correctly, thanks @dcramer !
Before this i used pip install --upgrade and don't completly uninstall the plugin, here is my fail i think.

Tyvm again.)

**Comment by temoto** [comment]
Affects me on Sentry 8.
Master works. 👍 
Comment to subscribe for release notification.
Thanks.
