### ISSUE TITLE
Cannot configure sentry-jira

### ISSUE THREAD

**Issue by UlTriX** [getsentry/sentry-jira#85]
I am using sentry 8.2.2 with sentry-jira 0.8.0

I activated the plugin correctly but when clicking Integrations > Jira and adding the 
URL, username and password after clicking save nothing happens.

The page reloads and the URL username and password  appear black.

I am trying to add an on premises jira server

**Comment by dcramer** [comment]
@UlTriX could you try latest git? `pip install https://github.com/getsentry/sentry-jira/archive/master.zip`

If the username/password are invalid at all, it _should_ be showing an error. The only other thing I can think of is that it has no access and the list of projects is empty so its hiding the other selectors. Maybe also confirm that the account is admin or similar.

**Comment by UlTriX** [comment]
Did not saw that there were newer versions of sentry-jira
With the latest it works! Thanks
