### ISSUE TITLE
unable to create issues in jira

### ISSUE THREAD

**Issue by ghost** [getsentry/sentry-jira#86]
Hello, 

I've tried everything I can think of but can;t seem to get an issue created in JIRA. 

Im using Jira on prem (v7.1.0) with Sentry on prem (v8.2.3) and the sentry-jira plugin (v 0.9.0) and cannot get to the second page with options to create the issue. (I presume there is a second page with options here similar to the gitlab integration?)

I've added credentials for an admin user on jira so permissions should not be an issue. I've configured the url, uname and password and that works because I get a list of projects to pick from - so creds and connection is being made.

When I click on an issue and go to More -> create Jira issue I get redirected to another sentry page with nothing there apart from the logo (networks tools show a 200 status code) but cant seem to load the content with fields to create the issue, logs aren't showing errors either. Disabled all browser plugins and still nothing, have tried different browsers and get nothing...  

Does anyone know what Im missing to get this working? I'd really appreciate any info, Im stumped... Let me know if you require more info from my end

Thanks

Cheers
Josh

**Comment by dcramer** [comment]
If you're getting a blank page that sounds like Sentry vs sentry-jira version incompat

Can you try `pip install https://github.com/getsentry/sentry-jira/archive/master.zip`

**Comment by ghost** [comment]
That did it :) Thanks for the pointer @dcramer, appreciate it

Im unsure why the release version doesn't work, but glad that the integration works :)
