### ISSUE TITLE
"Loading failed" on required field "Reporter" prevents integration from creating new issues

### ISSUE THREAD

**Issue by rmartin-chwy** [getsentry/sentry-jira#92]
Whenever we try to create a new issue via the JIRA integration, the Reporter dropdown will not load the list of users. I've tried giving the sentry user admin permissions in JIRA and it doesn't help. Since "reporter" is a required field, this prevents us from creating issues at all. I can't find a log or other information on the "loading failed," it seems to be hidden within Sentry.

Sentry 8.5.0
JIRA 7.0.5

**Comment by bsergean** [comment]
Does your service account has this permission ?

```
Modify reporter
Permission to modify the 'Reporter' of an issue. This allows a user to create issues 'on behalf of' someone else. This permission should generally only be granted to administrators.
```

**Comment by rmartin-chwy** [comment]
Apparently that permission was not included in the admin permission we’d given the Sentry account. We’ve fixed it now.

## 

Ryan Martin
Senior Software Engineer
E: rmartin@chewy.com
P: 786-320-7111 x1057
[cid:image001.png@01D1C7AF.DF5E52C0]

**Comment by bsergean** [comment]
Ah interesting. Did this fix the issue ?

**Comment by rmartin-chwy** [comment]
Yes, it did.

Get Outlook for Androidhttps://aka.ms/ghei36

On Thu, Jun 16, 2016 at 12:46 PM -0400, "Benjamin Sergeant" <notifications@github.com<mailto:notifications@github.com>> wrote:

Ah interesting. Did this fix the issue ?

> On Jun 16, 2016, at 6:17 AM, rmartin7c notifications@github.com wrote:
> 
> Apparently that permission was not included in the admin permission we'd given the Sentry account. We've fixed it now.
> 
> ## 
> 
> Ryan Martin
> Senior Software Engineer
> E: rmartin@chewy.com
> P: 786-320-7111 x1057
> [cid:image001.png@01D1C7AF.DF5E52C0]
> 
> From: Benjamin Sergeant notifications@github.com
> Reply-To: getsentry/sentry-jira reply@reply.github.com
> Date: Wednesday, June 15, 2016 at 10:42 PM
> To: getsentry/sentry-jira sentry-jira@noreply.github.com
> Cc: Ryan Martin rmartin@chewy.com, Author author@noreply.github.com
> Subject: Re: [getsentry/sentry-jira] "Loading failed" on required field "Reporter" prevents integration from creating new issues (#92)
> 
> Does your service account has this permission ?
> 
> Modify reporter
> 
> Permission to modify the 'Reporter' of an issue. This allows a user to create issues 'on behalf of' someone else. This permission should generally only be granted to administrators.
> 
> ## 
> 
> You are receiving this because you authored the thread.
> 
> ## Reply to this email directly, view it on GitHubhttps://github.com/getsentry/sentry-jira/issues/92#issuecomment-226374274, or mute the threadhttps://github.com/notifications/unsubscribe/APFwBl6BIXEc1pxrev3ZSRcQDESQT8roks5qMLgAgaJpZM4Ionkw.
> 
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub https://github.com/getsentry/sentry-jira/issues/92#issuecomment-226481849, or mute the thread https://github.com/notifications/unsubscribe/ALTvUQYSdD5MgW-PxbYL2sk-Bc2QTlpNks5qMUzjgaJpZM4Ionkw.

##

**Comment by bsergean** [comment]
Great ! 
Do you mind closing this issue in github ?
