### ISSUE TITLE
Put v0.10.0 on PyPi

### ISSUE THREAD

**Issue by Duologic** [getsentry/sentry-jira#94]
I've ran into this issue using sentry-jira==0.9.0: https://github.com/getsentry/sentry/issues/3001

Installing sentry-jira==0.10.0 (Github Release > tar.gz) seems to fix it.

Could you put sentry-jira==0.10.0 on PyPi so others can benefit from it too?

Thanks!

**Comment by bsergean** [comment]
Ran into that problem too ...

**Comment by dcramer** [comment]
Pushed 0.11.0. It looks like our deploys were broken for 0.10.0 so it never went live.

**Comment by bsergean** [comment]
Thanks !

**Comment by Duologic** [comment]
Great!

**Comment by bsergean** [comment]
Looks like this is the version that got pushed -> 0.11.0.dev0; the setup.py file probably wasn't changed. Not a big deal for me but maybe a bit confusing. Should the next version be 0.12.0, or can a 0.11.0 be released (maybe 0.11.1) ?

https://pypi.python.org/pypi/sentry-jira

**Comment by dcramer** [comment]
Doh. Pushing up now as 0.11.1 (though I think 0.11.0 would have taken priority).
