### ISSUE TITLE
"No schema supplied" when trying to create a ticket

### ISSUE THREAD

**Issue by danielgagnon-logient** [getsentry/sentry-jira#95]
I configured sentry-jira with a project and it connected to Jira just fine. However when I tried to create a jira ticket from a stacktrace, I got the following error:

`Error in request to jira.alogient.com/rest/api/2/priority: Invalid URL 'jira.alogient.com/rest/api/2/priority': No schema supplied. Perhaps you meant http://jira.alogient.com/rest/api/2/priority?`

Why would the https:// part be stripped when making that request?

Sentry version: 8.4.1  
sentry-jira version: 0.9.0

**Comment by dcramer** [comment]
Did you enter the instance URL with the schema included? I don't know what else would cause this.

**Comment by danielgagnon-logient** [comment]
Yes, https.

And as mentioned in the first line, the initial connection with JIRA works fine, I can see my JIRA project and pick the one I want from the dropbox just fine.

The schema is somehow stripped when I can to create a ticket.

**Comment by dcramer** [comment]
I am unfortunately unable to find any way for this to be possible unless its not entered in with HTTPS

**Comment by danielgagnon-logient** [comment]
Any way I can provide some logs that would help shed light on this?

**Comment by dcramer** [comment]
Could you dump the relevant rows from sentry_projectoption? Make sure to only grab instance_url, as password is unencrypted (we really should get away from this auth model).

**Comment by danielgagnon-logient** [comment]
``` id | project_id |                 key                 |                          value

----+------------+-------------------------------------+--------------------------------------------
 44 |          5 | jira:enabled                        | gAKILg==
gAJYIAAAAGIyYTM0YjFjMjgyMzExZTY4NWQzMDAxNTVkMDUwZDQwcQEu
 51 |          1 | jira:enabled                        | gAKILg==
 45 |          4 | jira:username                       | [removed]
 46 |          4 | jira:password                       | [removed]
 47 |          4 | jira:instance_url                   | gAJYGQAAAGh0dHBzOi8vamlyYS5hbG9naWVudC5jb21xAS4=xAS4=
 48 |          4 | jira:ignored_fields                 | gAJYAAAAAC4=
```

**Comment by danielgagnon-logient** [comment]
| id | project_id | key | value |
| --- | --- | --- | --- |
| 44 | 5 | jira:enabled | gAKILg== |
| 51 | 1 | jira:enabled | gAKILg== |
| 45 | 4 | jira:username | [removed] |
| 46 | 4 | jira:password | [removed] |
| 47 | 4 | jira:instance_url | gAJYGQAAAGh0dHBzOi8vamlyYS5hbG9naWVudC5jb21xAS4= |
| 48 | 4 | jira:ignored_fields | gAJYAAAAAC4= |

What kind of encoding is this in?!

**Comment by dcramer** [comment]
@danielgagnon-logient its pickled (Python's native serializer) and encoded via base64. I'll try to find more time to dig into this, but I'm stumped at the moment as the values look fine.

**Comment by danielgagnon-logient** [comment]
It also works fine in the config screen. Connects fine, lets me pick the project.

It's only when trying to actually creating the ticket that somethings happens.
